import { Router } from "express";
import { authRouter } from "./auth";
import { examRouter } from "./exams";
import { roadmapRouter } from "./roadmap";
import { adminRouter } from "./admin";
import { aiRouter } from "./ai";
import { metaRouter } from "./meta";
import { predictionRouter } from "./prediction";
import { interviewRouter } from "./interview";
import { activityRouter } from "./activity";
import { jobsRouter } from "./jobs";
import studyAssistantRouter from "./studyAssistant";
import resumeAnalyzerRouter from "./resumeAnalyzer";
import { alertsRouter } from "./alerts";
import { knowledgeRouter } from "./knowledge";
import { interviewV2Router } from "./interviewV2";
import { companyRouter } from "./company";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/exams", examRouter);
apiRouter.use("/roadmap", roadmapRouter);
apiRouter.use("/admin", adminRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/meta", metaRouter);
apiRouter.use("/prediction", predictionRouter);
apiRouter.use("/interview", interviewRouter);
apiRouter.use("/interview-v2", interviewV2Router);
apiRouter.use("/activity", activityRouter);
apiRouter.use("/jobs", jobsRouter);
apiRouter.use("/study-assistant", studyAssistantRouter);
apiRouter.use("/resume", resumeAnalyzerRouter);
apiRouter.use("/alerts", alertsRouter);
apiRouter.use("/knowledge", knowledgeRouter);
apiRouter.use("/company", companyRouter);
